name: Catalog Service

on:
  push:
    paths:
      - catalog-service/**
    branches:
      - '**'
#  pull_request:
#    branches: [main]

jobs:
  build:
    name: Build
    if: false     #--->>> UNCOMMENT AND WORKFLOW ACTION WILL WORK
    runs-on: ubuntu-latest
    env:
      working-directory: ./catalog-service
      DOCKER_IMAGE_NAME: dharmesh/bookstore-catalog-service
    defaults:
      run:
        working-directory: ${{env.working-directory}}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Build with Maven
        run: ./mvnw -ntp verify















