name: Order Service

on:
  push:
    paths:
      - order-service/**
    branches:
      - '**'
#  pull_request:
#    branches: [main]

jobs:
  build:
    name: Build
#    if: false     #--->>> UNCOMMENT AND WORKFLOW ACTION WILL WORK
    runs-on: ubuntu-latest
    env:
      working-directory: ./order-service
      DOCKER_IMAGE_NAME: sritikz/bookstore-order-service
      SHOULD_PUBLISH: ${{ github.ref == 'refs/heads/main' || github.event.inputs.publish_docker_image == 'true' }}

    defaults:
      run:
        working-directory: ${{env.working-directory}}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Build with Maven
        if: ${{ env.SHOULD_PUBLISH== 'false' }}
        run: ./mvnw -ntp verify



#      - name: Login to Docker Hub
#        if: ${{ env.SHOULD_PUBLISH== 'false' }}
#        uses: docker/login-action@v3
#
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#
#      - name: Build and Publish Docker Image
#        if: ${{ env.SHOULD_PUBLISH== 'false' }}
#
#        run: |
#           ./mvnw spring-boot:build-image -DskipTests
#           echo "Pushing the image $DOCKER_IMAGE_NAME to Docker Hub..."
#           docker push $DOCKER_IMAGE_NAME

